# 1. Install, Imports, Settings

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import spacy
from spacy.lang.es.examples import sentences 
#!python -m spacy download es_core_news_md
nlp = spacy.load("es_core_news_md")
from collections import Counter
import string, math, json

In [2]:
plt.rcParams["figure.figsize"] = [10, 6]
%config InlineBackend.figure_format = 'retina'

punct = string.punctuation +'”“'

# 2. Loading data

In [3]:
grupos = {
    "Grupo Armado Organizado" : ["GAO"],
    "Grupo Armado Ilegal" : ["GAI"],
    "Grupo Armado Organizado Residual" : ["GAOR", "GAO-R", "grupo armado organizado - residual" ], 
    "Ejército de Liberación Nacional" : ["ELN"],
    "Autodefensas Gaitanistas de Colombia" : ["AGC"],
    "Fuerzas Armadas Revolucionarias - Ejército del Pueblo" : ["FARC", 
                                         "Fuerzas Armadas Revolucionarias de Colombia",
                                         "Fuerzas Armadas Revolucionarias Ejército del Pueblo",
                                         "FARCEP", "FARC-EP", "FARC EP"
                                        ],
    "Grupo delincuencial organizado" : ["GDO", ],
    "Jalisco Nueva Generación": [],
    "Bandas Criminales" : ["BACRIM", "Bandas Emergentes"],
    "Autodefensas Unidas de Colombia" : ["AUC", ],
    "Grupos posdesmovilización": [],
    "Ejército de Liberación Popular": ["EPL"],
    "Clan del Golfo" : ["AGC"],
}

children = ["NNAJ", "niños", "niñas", "adolescentes", "jóvenes", "NNA"]

narco_grupos  = ["Cartel del Amazonas",  
        "Cartel de Los Nevados",
        "Cartel de Bogotá",
        "Cartel de Buga",
        "Cartel de Medellín",
        "Oficina de Envigado",
        "Cartel de Cali",
        "Cartel del Caquetá",
        "Cartel del Norte del Valle",
        "Los Rastrojos",
        "Cartel de la Costa Atlántica",
        "Cartel de La Guajira",
        "Cartel del Cauca",
        "Los Caparrapos",
        "Los Paisas",
        "Águilas Negras",
        "Los Puntilleros",
        "Ejército Revolucionario Popular Antisubversivo de Colombia",
        "Los Pelusos",
        "GDO Los Pachenca",
        "Clan Gnecco Cerchar",
        "Clan Bustamante", 
        "Activo Primer Frente",
        "Segunda Marquetalia", 
        "Los Zetas", 
        "Cartel de Sinaloa", 
        "Oficina de Envigado", 
        "La Terraza",
        "Robledo",
        "Pachelly",
        "La Sierra", 
        "Caicedo", 
        "Los Triana",
        "Clan del Oriente", 
        "La Unión",
        "Clan del Norte",
        "Los Costeños", 
        "Los Pachencha", 
        "La Cordillera",
        "La Gran Alianza",
        "Banda Local",
        "Norte del Valle",
        "Los Chuckys",
        "Los Chacales",
        "La Constru",
        "Los Caqueteños"]

POI = {
    "Evaristo Porras": "Papa Doc",
    "Luis Agustín Caicedo Velandia" : "Don Lucho", 
    "Víctor Manuel Mejía Múnera": "Pablo Arauca",
    "Miguel Ángel Mejía Múnera": "El Mellizo",
    "Ramón Quintero":"",
    "Pablo Escobar" : "El patrón",
    "Gonzalo Rodríguez Gacha": "",
    "Diego Fernando Murillo": "",
    "Gilberto Rodríguez Orejuela": "El Ajedrecista",
    "Miguel Rodríguez Orejuela": "",
    "Leonidas Vargas": "El Rey de Caquetá",
    "Luis Enrique Calle Serna": "",
    "Wilber Varela": "",
    "Alberto Orlandez Gamboa": "", 
    "Hermágoras González": "",
    "Nicolás Rodríguez Bautista" : " Gabino ", 
    "Iván Márquez": "",
    "Gentil Duarte": "",
    "Jorge Gnecco Cerchar": "", 
    "Jesús María Aguirre" :"Chucho Mercancía",
    "Megateo": "",  
    "Vicente Castaño": "", 
    "Emiliano Alcides Osorio": " Caín ",
    "Edgar Bustamante" : "El Yuca",
    "Manuel Marulanda Vélez" :" Tirofijo ",     
    "Jorge Briceño Suarez Mono": " Jojoy ",
    "Dairo Antonio Úsuga David": "",
    "Salvatore Mancuso": "",
    "Rodrigo Tovar": "",
    "Carlos Castaño Gil": "",
    "Justo Pastor Perafán": "Don Pepe"
}

loc = pd.read_csv("resources/Departamentos_y_municipios_de_Colombia.csv")
loc.head()

,REGION,CÓDIGO DANE DEL DEPARTAMENTO,DEPARTAMENTO,CÓDIGO DANE DEL MUNICIPIO,MUNICIPIO
0,Región Eje Cafetero - Antioquia,5,Antioquia,5.001,Medellín
1,Región Eje Cafetero - Antioquia,5,Antioquia,5.002,Abejorral
2,Región Eje Cafetero - Antioquia,5,Antioquia,5.004,Abriaquí
3,Región Eje Cafetero - Antioquia,5,Antioquia,5.021,Alejandría
4,Región Eje Cafetero - Antioquia,5,Antioquia,5.030,Amagá

In [4]:
df = pd.read_csv("data/alertas_actors.csv", sep="|")

print("Total Number of documents:", len(df))

Total Number of documents: 1753

In [5]:
df.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Filename,Subtype,Type,Year,Path,Departamento,Actors
0,0,0,0,"AT N° 003-18 NAR-Cumbitara, Maguí Payán, Polic...",Alerta Temprana,Advertencia,2018,data\Advertencia_PDF\AT 2018\AT N° 003-18 NAR-...,Nariño,"['Grupo Armado Ilegal', 'Grupo Armado Ilegal',..."
1,1,1,1,AT N° 004-18 NAR-Tumaco.pdf,Alerta Temprana,Advertencia,2018,data\Advertencia_PDF\AT 2018\AT N° 004-18 NAR-...,Nariño,"['Grupo Armado Ilegal', 'Grupo Armado Ilegal',..."
2,2,2,2,AT N° 005-18 COR-Tierralta.pdf,Alerta Temprana,Advertencia,2018,data\Advertencia_PDF\AT 2018\AT N° 005-18 COR-...,Córdoba,"['Grupo Armado Ilegal', 'Grupo Armado Ilegal',..."
3,3,3,3,AT N° 006-18 ARA-Saravena.pdf,Alerta Temprana,Advertencia,2018,data\Advertencia_PDF\AT 2018\AT N° 006-18 ARA-...,Arauca,"['Grupo Armado Ilegal', 'Grupo Armado Ilegal',..."
4,4,4,4,"AT N° 007-18 MET-Puerto Lleras, Puerto Rico y ...",Alerta Temprana,Advertencia,2018,data\Advertencia_PDF\AT 2018\AT N° 007-18 MET-...,Meta,"['Grupo Armado Organizado', 'Grupo Armado Orga..."

# 3. Cleaning Duty

In [71]:
arts = ['la', 'los', 'el', 'las', 'una', 'un']
def replace_accents(w):
    return w.replace('á','a').replace('é','e').replace('í','i').replace('ó','o').replace('ú','u')

arts = ['la', 'los', 'el', 'las', 'una', 'un']
def replace_articles(w):
    w = [x for x in w.split() if x not in arts]
    return ' '.join(w)

def clean_segment(s):
    return replace_articles(replace_accents(s.lower()))
    
def clean_actors(entities):
    entities = entities.strip("']['").split("', '")
   
    if len(entities) == 0:
        return []
    
    #grupos
    for key, value in grupos.items():
        for v in value:
            entities = [key if clean_segment(e) == clean_segment(v) else e for e in entities]
           
    #narco grupos
    for v in narco_grupos:
        entities = [v if clean_segment(e) == clean_segment(v) else e for e in entities]
    return entities

df["Actors"] = df["Actors"].apply(clean_actors)

In [73]:
df.to_csv("data/alertas_actors.csv", sep="|")

In [72]:
df.head()

,Unnamed: 0.1,Unnamed: 0,Filename,Subtype,Type,Year,Path,Departamento,Actors
0,0,0,"AT N° 003-18 NAR-Cumbitara, Maguí Payán, Polic...",Alerta Temprana,Advertencia,2018,data\Advertencia_PDF\AT 2018\AT N° 003-18 NAR-...,Nariño,"[Grupo Armado Ilegal, Grupo Armado Ilegal, Aut..."
1,1,1,AT N° 004-18 NAR-Tumaco.pdf,Alerta Temprana,Advertencia,2018,data\Advertencia_PDF\AT 2018\AT N° 004-18 NAR-...,Nariño,"[Grupo Armado Ilegal, Grupo Armado Ilegal, Gru..."
2,2,2,AT N° 005-18 COR-Tierralta.pdf,Alerta Temprana,Advertencia,2018,data\Advertencia_PDF\AT 2018\AT N° 005-18 COR-...,Córdoba,"[Grupo Armado Ilegal, Grupo Armado Ilegal, Ejé..."
3,3,3,AT N° 006-18 ARA-Saravena.pdf,Alerta Temprana,Advertencia,2018,data\Advertencia_PDF\AT 2018\AT N° 006-18 ARA-...,Arauca,"[Grupo Armado Ilegal, Grupo Armado Ilegal, Ejé..."
4,4,4,"AT N° 007-18 MET-Puerto Lleras, Puerto Rico y ...",Alerta Temprana,Advertencia,2018,data\Advertencia_PDF\AT 2018\AT N° 007-18 MET-...,Meta,"[Grupo Armado Organizado, Grupo Armado Organiz..."

# 4. Functions

In [6]:
df = pd.read_csv("data/alertas_actors.csv", sep="|")

In [7]:
space_articles = []
red_flags = ['Telefax', 'procesoSubproceso Prevención y Protección Código','SAT', 'Alerta Temprana', 
             'Derecho Internacional Humanitario', 'SAT Código DPR', 
             'procesoSubproceso Prevención y Protección Código PPP02F10 ALERTA', 'SEGUIMIENTO', 
             'PARA', 'Frente', 'Nota de Seguimiento', 'PP', 'AT', 'LIBERTAD',  'Alertas Tempranas', 
             'P01 F07 Formato Nota de Seguimiento Versión 03 Vigente', 
             'Prevención y Protección Código PP', 'Bloque C', 'Comisión', 'POBLACION','Constitución Política', 
             'procesoSubproceso Prevención y Protección Código PP', 'Ejército', 'Sin', 'INFORME', 'MUSE', 
             'BIENES INDISPENSABLES PARA', 'Gobernación', 'A NO SER', 'cia', 'Alerta']

arts = ['la', 'los', 'el', 'las']

In [8]:
def remove_flags(entities):
     return [e for e in entities if e not in red_flags]

def remove_articles(entities):
    new = []
    for i in range(0, len(entities) - 1):
            new.append(entities[i])
            for a in arts:
                if entities[i].lower().startswith(a + " "):
                    new[len(new)-1] = entities[i][len(a):]

    return new
                     
def fix_terms(entities):
    new = []
    for i in range(0, len(entities)):
        new.append(entities[i])
        # fix ELN
        if entities[i].startswith("ELN "):
                   new[len(new) - 1] =  "Ejército de Liberación Nacional"
        #fix Las FARC           
        elif entities[i].startswith("FARC") or entities[i].startswith("lasFARC") or entities[i].startswith("LasFARC"):
                   new[len(new) - 1] = "Fuerzas Armadas Revolucionarias - Ejército del Pueblo" 
                
        elif entities[i].startswith("Fuerzas Armadas Revolucionarias"):
                   new[len(new) - 1] = "Fuerzas Armadas Revolucionarias - Ejército del Pueblo" 
                
        elif entities[i].lower().startswith("urabe"):
                   new[len(new) - 1] = "Urabeños"     
                
        elif entities[i].startswith("UNP"):
                   new[len(new) - 1] = "Unidad Nacional de Protección"    
        
        elif entities[i].startswith("Acción Social"):
                   new[len(new) - 1] = "Agencia Presidencial para la Acción Social"
                
        elif entities[i].startswith("Al Instituto Colombiano de Bienestar Familiar"):
                   new[len(new) - 1] = "Instituto Colombiano de Bienestar Familiar"
                
        elif entities[i].lower().startswith("armada"):
                   new[len(new) - 1] = "Armada Nacional"
                
        elif entities[i].lower().startswith("defensor"):
                   new[len(new) - 1] = "Defensoría del Pueblo"
                
    return new

def clean_list_actors(df):
    actors = df.Actors.sum()
    if type(actors) == str:
        actors = actors.strip("']['").split("', '")
    
    #remove articles
    actors = remove_articles(actors)
                     
    #fix some terms
    actors = fix_terms(actors)                               
                
    #remove red flags
    actors = remove_flags(actors)
    
    #remove blank spaces
    actors = [a.strip() for a in actors]
    
    return actors
    
def most_mentioned_actors(actors):           
    data = { 
             'actors': list(Counter(actors).keys()), 
             'frequency': list(Counter(actors).values())
           }

    counterdf = pd.DataFrame(data)
    counterdf = counterdf.groupby('actors').agg({'frequency' : 'sum'}).sort_values('frequency', ascending = False)
    return counterdf

# 4. Most Mentioned Actors - 50 in General

#### Los articulos se omiten por cuestiones de estandarizacion de los datos, pero por ejemplo Rastrojos se refiere a Los Rastrojos que es el nombre original.

In [9]:
dfa = most_mentioned_actors(clean_list_actors(df))
dfa[:50]

                                                    frequency
actors
Fuerzas Armadas Revolucionarias - Ejército del ...      14083
Autodefensas Unidas de Colombia                          6916
Ejército de Liberación Nacional                          6772
Fuerza Pública                                           5325
Águilas Negras                                           3624
Policía Nacional                                         2687
Rastrojos                                                2683
Autodefensas Gaitanistas de Colombia                     2185
Grupo Armado Ilegal                                      1753
Constru                                                  1507
Urabeños                                                 1402
Policía                                                  1361
Unidad Nacional de Protección                            1236
Cordillera                                               1064
Agencia Presidencial para la Acción Social                972
Unión                                                     958
Fiscalía General de la Nación                             937
Instituto Colombiano de Bienestar Familiar                902
Sierra                                                    839
Ejército de Liberación Popular                            833
Paisas                                                    809
Corte Constitucional                                      758
Acción Comunal                                            728
Defensoría del Pueblo                                     689
Unidad para la Atención                                   617
Armada Nacional                                           607
Alcaldías                                                 597
Autodefensas                                              577
Oficina de Envigado                                       471
Ejército Nacional                                         458
Caicedo                                                   393
JAC                                                       328
MAP                                                       298
Grupos posdesmovilización                                 268
Vicepresidencia de la República                           261
Clan del Golfo                                            261
Oficina del Alto Comisionado para la Paz                  249
Frente Primero                                            247
Plantilla Vigente                                         230
Ejercito Nacional                                         229
Norte del Valle                                           223
Bloque Central                                            222
Red de Solidaridad Social                                 221
Comisión Intersectorial para la Respuesta Rápid...        215
ICBF                                                      214
NBI                                                       213
Comisión Intersectorial de Alertas Tempranas              211
UARIV                                                     207
OEA                                                       204
Bandas Criminales                                         203

# 5. Statistical Distribution of Actors

In [10]:
dfa[dfa.frequency > 100].describe()

          frequency
count    123.000000
mean     647.243902
std     1631.719742
min      101.000000
25%      133.500000
50%      179.000000
75%      360.500000
max    14083.000000

# 6. Top 10 actors in each period

In [13]:
df1 = df[df.Year < 2006]
df2 = df[(df.Year > 2005) & (df.Year < 2012)]
df3 = df[(df.Year > 2011) & (df.Year < 2017)]
df4 = df[df.Year > 2016]

# 6.1 2001 - 2005 (Conflicto, 2005 Justicia y Paz)

In [21]:
df1 = most_mentioned_actors(clean_list_actors(df1))[:10]
df1

                                                    frequency
actors
Fuerzas Armadas Revolucionarias - Ejército del ...       2410
Autodefensas Unidas de Colombia                          2204
Ejército de Liberación Nacional                           531
Fuerza Pública                                            513
Autodefensas                                              409
Red de Solidaridad Social                                 215
Armada Nacional                                           203
Sierra                                                    144
Policía                                                   126
Cordillera                                                121

In [22]:
df1[df1.frequency > 100].describe()

         frequency
count    10.000000
mean    687.600000
std     868.515745
min     121.000000
25%     158.750000
50%     312.000000
75%     526.500000
max    2410.000000

# 6.2 2006- 2011 (Conflicto)

In [23]:
df2 = most_mentioned_actors(clean_list_actors(df2))[:10]
df2

                                                    frequency
actors
Fuerzas Armadas Revolucionarias - Ejército del ...       3916
Autodefensas Unidas de Colombia                          2149
Águilas Negras                                           1905
Fuerza Pública                                           1653
Ejército de Liberación Nacional                          1085
Rastrojos                                                1032
Agencia Presidencial para la Acción Social                917
Policía Nacional                                          488
Grupo Armado Ilegal                                       451
Policía                                                   409

In [24]:
df2[df2.frequency > 100].describe()

         frequency
count    10.000000
mean   1400.500000
std    1074.587906
min     409.000000
25%     595.250000
50%    1058.500000
75%    1842.000000
max    3916.000000

# 6.3 2012 - 2016 (Negociaciones de Paz, Acuerdo de La Habana)

In [25]:
df3 = most_mentioned_actors(clean_list_actors(df3))[:10]
df3

                                                    frequency
actors
Fuerzas Armadas Revolucionarias - Ejército del ...       3301
Fuerza Pública                                           1328
Ejército de Liberación Nacional                          1305
Rastrojos                                                1264
Autodefensas Unidas de Colombia                          1155
Águilas Negras                                           1108
Urabeños                                                 1085
Autodefensas Gaitanistas de Colombia                      782
Policía Nacional                                          707
Grupo Armado Ilegal                                       593

In [26]:
df3[df3.frequency > 100].describe()

        frequency
count    10.00000
mean   1262.80000
std     761.30032
min     593.00000
25%     857.75000
50%    1131.50000
75%    1294.75000
max    3301.00000

# 6.4 2017 - 2022 (Post- Acuerdo)

In [27]:
df4 = most_mentioned_actors(clean_list_actors(df4))[:10]
df4

                                                    frequency
actors
Fuerzas Armadas Revolucionarias - Ejército del ...       4456
Ejército de Liberación Nacional                          3851
Fuerza Pública                                           1831
Autodefensas Unidas de Colombia                          1408
Policía Nacional                                         1400
Autodefensas Gaitanistas de Colombia                     1203
Constru                                                   994
Unidad Nacional de Protección                             971
Grupo Armado Ilegal                                       701
Águilas Negras                                            611

In [28]:
df4[df4.frequency > 100].describe()

         frequency
count    10.000000
mean   1742.600000
std    1327.379306
min     611.000000
25%     976.750000
50%    1301.500000
75%    1725.250000
max    4456.000000

# 6. Export HTML

In [33]:
!jupyter nbconvert --to html 6_Mapping_Actores_del_Conflicto.ipynb

[NbConvertApp] Converting notebook 6_Mapping_Actores_del_Conflicto.ipynb to html
[NbConvertApp] Writing 675914 bytes to 6_Mapping_Actores_del_Conflicto.html